### ISSUE TITLE
Animation glitch for red crab thing

### ISSUE THREAD

**Issue by Tybobobo** [Hirnbix/captain-holetooth#12]
The red crab thing suddenly turns into this every x frames of an animation.
![image](https://cloud.githubusercontent.com/assets/6776092/19446553/a355cef4-9499-11e6-8248-5844f99d3053.png)

Most of the animation, it looks like this.
![image](https://cloud.githubusercontent.com/assets/6776092/19446586/c20faeb4-9499-11e6-85db-72a0d440a257.png)

Remove the weird one, or make more animation frames for the first (devil-looking) sprite?

**Comment by oliver-ruehl** [comment]
yeah, i was too lazy to fix this
But its on my list

**Comment by oliver-ruehl** [comment]
I'll call him "**Recrath**" (REd CRAb THing)

**Comment by oliver-ruehl** [comment]
Recrath has been updated, still working on walking animation
