### ISSUE TITLE
Game not working right now

### ISSUE THREAD

**Issue by oliver-ruehl** [Hirnbix/captain-holetooth#12]
The Menu Screen produces a loop, you can't switch scenes.

**Comment by oliver-ruehl** [comment]
How come the sample lib breaks the game? Just curious :)

**Comment by jjay** [comment]
There was broken asset, it crashes my editor as well as game. It is how Godot works - if it can't load some part of scene, it wouldn't load the whole scene. Just for attention.
And you know, it is open source )

**Comment by oliver-ruehl** [comment]
Ok thanks i learned a lot!
