### ISSUE TITLE
When coins are hit by the player bullet, they are collected

### ISSUE THREAD

**Issue by oliver-ruehl** [Hirnbix/captain-holetooth#15]
Actually, I like the idea (for later!):

- Player standard weapon: Candy Bullet (effective against enemies)
- Player picks up candy bullet "upgrade": Candy Bullet can now collect items and makes it easier to get to harder to reach places :)

But right now its distracting especially in the ship level, because you hit something and the item disappears. There is no visual feedback.

**Comment by jjay** [comment]
#17 also also affects this.
