### ISSUE TITLE
Missing scenes for tilesets

### ISSUE THREAD

**Issue by Tybobobo** [Hirnbix/captain-holetooth#16]
There is no apparent TileSet scene for Castle or Forest.
This means it will be challenging to edit the tilesets later.

We should recreate the tilesets and save it as a scene so that we can easily make modifications and covert it to an updated tileset.

**Comment by Tybobobo** [comment]
I see you have added tileset for Mountain and Castle. The tileset.tscn for Forest is currently completely empty though.

**Comment by oliver-ruehl** [comment]
Done
