### ISSUE TITLE
Audio clip for jumping does not feel like the character

### ISSUE THREAD

**Issue by Tybobobo** [Hirnbix/captain-holetooth#17]
When I look at this character, I do not believe the voice that the jumping voice is his. 
On first impression, I get the impression he has a bit of a scrawny voice, not a deep "Huff!" :)

**Comment by oliver-ruehl** [comment]
I have scheduled a session with my son to record some samples :)

**Comment by oliver-ruehl** [comment]
Can we implment this globally so that ugly looping is not possible for SFX?

**Comment by oliver-ruehl** [comment]
Added my sons voice. Im happy with the result
