### ISSUE TITLE
Level Design: When jumping down the hole, you cant get up

### ISSUE THREAD

**Issue by Tybobobo** [Hirnbix/captain-holetooth#18]
![image](https://cloud.githubusercontent.com/assets/6776092/19477520/ce09f6de-953e-11e6-8d37-787531572524.png)

If you jump down, you cant get back up

**Comment by oliver-ruehl** [comment]
Level design is my thing, but its a lot of work lol

**Comment by Tybobobo** [comment]
Did a quick fix. Added a tiny platform on the side the player can jump on to, in order to get out. :3
https://github.com/Tybobobo/captain-holetooth/tree/Fixing-Issues

**Comment by Tybobobo** [comment]
Fixed in https://github.com/Hirnbix/captain-holetooth/pull/33
(when a level is incomplete, adding temporary walls or access should be made so that we can create test builds for the public, no?)
