### ISSUE TITLE
Snowy Mountains Level: Moving in the same direction as clouds make them move faster

### ISSUE THREAD

**Issue by Tybobobo** [Hirnbix/captain-holetooth#19]
![image](https://cloud.githubusercontent.com/assets/6776092/19478177/cb2350a2-9541-11e6-9ca3-e81c7d64d37e.png)

The clouds in the background move faster when I move in the same direction as them, and slower if I move in the opposite direction. It should be reversed

**Comment by oliver-ruehl** [comment]
Removed the animation
