### ISSUE TITLE
Background texture in Snowy Mountains level have some random pixels in it that does not appear to belong

### ISSUE THREAD

**Issue by Tybobobo** [Hirnbix/captain-holetooth#21]
![image](https://cloud.githubusercontent.com/assets/6776092/19479038/2e546884-9545-11e6-8eeb-5e026f762aca.png)

It does not look like it belong there :)

**Comment by oliver-ruehl** [comment]
My art problems :)

**Comment by Tybobobo** [comment]
Did you fix it? Communication 1

**Comment by oliver-ruehl** [comment]
fixed
