### ISSUE TITLE
Frame rate stuttering on low end android devices

### ISSUE THREAD

**Issue by oliver-ruehl** [Hirnbix/captain-holetooth#23]
Happening in the mountain level.
Just a reminder to reduce particles and maybe slimming down the torch effects

**Comment by Tybobobo** [comment]
Perhaps there is a way to check if you are playing on PC or Android on startup and load settings accordingly. Alternatively we could write an export script that allows you to select the settings before exporting. The latter I know how to do, but I have not previously worked with Android :)

**Comment by oliver-ruehl** [comment]
Got other reports about stuttering in mountain / snow level.
Too much particles I guess

**Comment by oliver-ruehl** [comment]
Removed the normal mapping. Much better ;)
