### ISSUE TITLE
Flyhome scene - Add transition to castle scene

### ISSUE THREAD

**Issue by oliver-ruehl** [Hirnbix/captain-holetooth#28]
I wrote this, but it only works for the jump n run part:

https://github.com/Hirnbix/captain-holetooth/blob/master/src/scene_teleporter.gd

**Comment by Tybobobo** [comment]
Fixed in https://github.com/Hirnbix/captain-holetooth/pull/33

**Comment by oliver-ruehl** [comment]
Can we use the "race finish line" for the whole project? It looks like we have a duplicate here.
Maybe with an option to add custom art.
