### ISSUE TITLE
Full controller support on PC

### ISSUE THREAD

**Issue by ivanskodje** [Hirnbix/captain-holetooth#30]
TODO :)

**Comment by oliver-ruehl** [comment]
Which controllers are we going to support?

**Comment by Tybobobo** [comment]
All of them! 
(Xbox, PS2, generics)

**Comment by oliver-ruehl** [comment]
Can you shed some light on how we can test this? :)

**Comment by Tybobobo** [comment]
I have an xbox controller, and Godot is mapping all of the controllers using the same binding (Y on Xbox Controller would be the equivalent of Triangle on Playstation Controller)

**Comment by oliver-ruehl** [comment]
Ok, I have a ps4 and can test on there

**Comment by oliver-ruehl** [comment]
Tests successful on MacOS Sierra, PS4 Controller

**Comment by AlexHolly** [comment]
Is someone working on this?

**Comment by oliver-ruehl** [comment]
Not really. I've tested the "ground levels" and in flight the ps4 controller does not work yet.
Also the GUI/HUD does not support any controller movement yet.
I'm pretty bad at understanding the controls in GUI really... just havent looked deep into it.
So.. No ;)

**Comment by AlexHolly** [comment]
Godot is already doing a good job for all kind of controllers I tried Xbox and Microsoft Sidewinder Dual Strike.

**Comment by HummusSamurai** [comment]
I don't understand this issue, is there some specific issue that needs to be addressed (it could be there was an issue but recent Godot versions fixed it).
