### ISSUE TITLE
NPCs pick up candy

### ISSUE THREAD

**Issue by oliver-ruehl** [Hirnbix/captain-holetooth#32]
I guess we need a function so that only the "player" actor can pick up items.
When you enter the forest level for example its chiming and it seems to me that NPCs walk over rewards :D

**Comment by Tybobobo** [comment]
Todo: Use groups to check for "player" on enter area for the item

**Comment by oliver-ruehl** [comment]
Does it make sense to make groups like "enemies" "story_characters" etc. ?

**Comment by oliver-ruehl** [comment]
This might be fixable like #37 with collision layers-
