### ISSUE TITLE
Create a toggle between Debug build and an Release build

### ISSUE THREAD

**Issue by Tybobobo** [Hirnbix/captain-holetooth#36]
If we were to compile this game and send to people, they would get access to "features" that should not be included: R for reset and the debug menu. We could create an debug toggler, that is set on the main scene so that we just change it to "Release" when we are compiling for other people to play.

**Comment by oliver-ruehl** [comment]
I agree im longing for this feature too :)

**Comment by AlexHolly** [comment]
I had a crash on the first uasge of "r" some hightscore stuff was missing.

```
func _input(e):
	if e.is_action_pressed("reload") && global.debug_mode:
		score = 0
		db = {"high_score":db["high_score"]} # save only high_score on reload
		save_game()
		load_game()
		emit_signal("scores_changed")
		get_tree().reload_current_scene()
```

**Comment by shelltitan** [comment]
@AlexHolly can you be more specific because I cannot reproduce it on my machine.

**Comment by AlexHolly** [comment]
1. Go to the godot User folder and delete the save file.
On
 windows(AppData\Roaming\Godot\app_userdata\CaptainHoletooth)
 linux something like (~/Godot/app_userdata/Captain Holetooth)
2.Start the game and press r.

The save file is only created when you talk with the old man.

**Comment by shelltitan** [comment]
I thought it was related to my commit but I fix this tomorrow.

**Comment by shelltitan** [comment]
@AlexHolly But if you switch to debug_mode = 0, you don't have to deal with it. :smile:

**Comment by shelltitan** [comment]
@AlexHolly Is it okay now?
