### ISSUE TITLE
Soap bubbles can't be popped in forest level

### ISSUE THREAD

**Issue by oliver-ruehl** [Hirnbix/captain-holetooth#37]
- I was a bit naive and just put the bubbles into the forest level.
- Used the proper groups, but the soaps don't pop when shot

I guess it's just my bad logic thinking :)
Would be nice to use them in other places no?

**Comment by Tybobobo** [comment]
Todo: Set "player_shot" group on the bullets

**Comment by oliver-ruehl** [comment]
I did, but the soap bubble don't care

**Comment by oliver-ruehl** [comment]
I know what causes this: Collision masks.
Need to study them to get anything to work 👍

**Comment by oliver-ruehl** [comment]
Anyone has ressources this month to get this BETA done at all?
Just asking ;) We can delay it if needed.
