### ISSUE TITLE
Pressing and holding R makes it loop reset

### ISSUE THREAD

**Issue by Tybobobo** [Hirnbix/captain-holetooth#4]
When you press R, sometimes it resets twice or more. If you hold R down, it remains in a reset loop. This should not happen, and should be fixed.

**Comment by Tybobobo** [comment]
Fixed: https://github.com/Tybobobo/captain-holetooth/tree/enhancements-and-fixes
Will make pull request after I am done with other tasks

**Comment by oliver-ruehl** [comment]
This remains in the game just for testing purposes.
The game is about collecting stuff (damn i really need to write the concept!!!)

**Comment by Tybobobo** [comment]
Why is this open? The issue was about the looping when you press R, not the functionality of R

**Comment by oliver-ruehl** [comment]
i didnt understand correctly
