### ISSUE TITLE
Idea for persistent level data

### ISSUE THREAD

**Issue by YeOldeDM** [Hirnbix/captain-holetooth#5]
Regarding the request for a way to keep enemy deaths permenant (so they don't respawn when you re-visit the area).

The first step would be to keep some global database of all enemies encountered so far (they can be appended as new areas are visited for the first time), and a flag which indicates whether or not they've been killed yet.
It might look something like:
```
var kills = {
	'level1': {
		'mob1': false,
		'mob2': false,
		..
		},
	'level2: {
		'mob1': false,
		'mob2': false,
		..
		},
	}
```

Next, rather than having instances of the enemies directly in your levels, make a Position2D object which will spawn the enemy, but only if its corresponding entry in the global database does not have that flag as True.

When a new level is initiated, have something along the lines of this in its _ready() function:
```
	func _ready():
# Make a new global entry if it's not there already
	if get_name() not in Globals.kills:
		var N = get_name()
		Globals.kills[N)] = {}
		for mob in get_node('enemies').get_children():
			if mob.get_name() not in Globals.kills[N]:
				Globals.kills[N][mob.get_name()] = false
# Check global database and only spawn enemies that haven't been flagged as dead
	for mob in get_node('enemies').get_children():
		if Globals.kills[N][mob.get_name()] == false:
			mob.spawn_enemy()
```

When an enemy is killed, make its flag true in the kills dictionary:
```
func _die():
	var level = ((reference to enemy's level's name))
	var spawner = ((reference to the spawner that made this enemy))
	
	# flag our spawner as dead
	Globals.kills[level][spawner] = true
```

**Comment by oliver-ruehl** [comment]
Thanks for the lesson :) Id rather keep the enemy instances where they are, i need more experience before i get more abstract. But Im happy to have you as a casual mentor ;)

**Comment by YeOldeDM** [comment]
I suggest making yourself a small prototype, to figure out the particulars of the system (I can guarantee you it probably isn't going to work 100% like I posted above). Make a couple small levels you can walk between, and set up a few spawners there to to play with.
After that is all figured out, it should just be a matter of replacing enemy instances with spawner instances.

**Comment by oliver-ruehl** [comment]
Yep a tiny prototype scene is a great idea.

**Comment by oliver-ruehl** [comment]
I will work on this tonight :) I like the idea with the position nodes, they are pretty useful for a lot of stuff :)

**Comment by oliver-ruehl** [comment]
I'm experimenting here :)
https://github.com/oliver-ruehl/godot-engine-persistence

**Comment by oliver-ruehl** [comment]
Hi YeOldeDM :) We made some great progress thanks to jjay - we've solved the problem with a database that reads and writes states (similar to your suggestions).
