### ISSUE TITLE
Text in the intro blends in images

### ISSUE THREAD

**Issue by Tybobobo** [Hirnbix/captain-holetooth#5]
After starting a new game, the text becomes partially unreadable.

![image](https://cloud.githubusercontent.com/assets/6776092/19445886/7dd19d32-9496-11e6-8b71-216abe6ba197.png)

This can be fixed by adding outlines to the font, changing the font colors or adding soft and semi-opaque background behind the text.

**Comment by Tybobobo** [comment]
The text position has changed a bit in the latest build, however the issue remains

**Comment by Tybobobo** [comment]
Fixed: https://github.com/Tybobobo/captain-holetooth/tree/enhancements-and-fixes
Will make pull request once I have fixed more issues :)

**Comment by oliver-ruehl** [comment]
art stuff
