### ISSUE TITLE
Cannot turn on music after turning it off

### ISSUE THREAD

**Issue by Tybobobo** [Hirnbix/captain-holetooth#6]
When you are ingame and press "Music Off", the music disappears and does not allow me to enable it.
The text does also not change.

![image](https://cloud.githubusercontent.com/assets/6776092/19445977/f3e3cd10-9496-11e6-93a7-b7d68affb151.png)

**Suggested fix:**
When you press the button, toggle to "Music On" and make it so when pressing the button again, the music resumes.

**Comment by Tybobobo** [comment]
Fixed: https://github.com/Tybobobo/captain-holetooth/tree/enhancements-and-fixes

I have also added an sound on/off image - one step in the right direction of getting rid of Godot's default buttons :)

![image](https://cloud.githubusercontent.com/assets/6776092/19459093/fc02a478-94d0-11e6-8b67-34760f739f50.png)

**Comment by oliver-ruehl** [comment]
We should add this later to the menu - i just did this for debugging

**Comment by Tybobobo** [comment]
Okay - so we can close this? 
For future plans, making an separate issue where you write about moving it to the menu might be a better approach than keeping this open

**Comment by oliver-ruehl** [comment]
agreed, closed
