### ISSUE TITLE
Figure out how we can test on some devices to be sure the touchscreen controls work

### ISSUE THREAD

**Issue by shelltitan** [Hirnbix/captain-holetooth#63]
You can set up mobile phone virtual machines and you can set it to specific phone so you can check it how would it look like. The only thing that not so accurate is the mouse clicking compared to using fingers. (You can set the android version etc.)

**Comment by oliver-ruehl** [comment]
Yeah i tried these virtual machines on my old mac - were pretty slow, but ill try again with my new mac. Android is not the priority at the moment, I'd rather get the game to work as a whole.
