### ISSUE TITLE
"Main Menu" : A misleading button or perhaps missing functionality

### ISSUE THREAD

**Issue by Tybobobo** [Hirnbix/captain-holetooth#7]
Since I am a bit unsure of the main intentions behind this button, there are two scenarios that you may want to happen depending on the intentions of this button. :)

![image](https://cloud.githubusercontent.com/assets/6776092/19446184/e5bf95b0-9497-11e6-8865-63d0b5311a3a.png)

**Scenario 1:** 
If you are playing and press the big button that says "Main Menu" (accidentally or not), it ends the game instantly without informing the player that this will cause the game to end. By adding a confirmation dialogue, we can prevent accidents and make sure users are informed that this action will end the game.

**Scenario 2:**
However, if the intention of this button is to allow for people to return to, say, the Options menu to make changes; we could pause the game, load the main menu, change the Start Game button to a "Continue", and allow the user to return to where s/he was when Continue has been pressed.

**Comment by oliver-ruehl** [comment]
Its just a debug button
