### ISSUE TITLE
Cleanup Errors

### ISSUE THREAD

**Issue by AlexHolly** [Hirnbix/captain-holetooth#80]
Play the game for a few secons and you will see many errors.

What are the plans for these two?

pin.gd:62
`get_node("sfx").play("tin")`

soap_bubble.gd:13
`animation.play("soap_pop")`

**Comment by oliver-ruehl** [comment]
what exactly are the errors?

**Comment by AlexHolly** [comment]
No six tin availabless and
No animation soap_pop available
